accelerate launch --config-file "configs/train_multigpu.yaml" train_sd15_dpo_corrupted.py \
    --mixed_precision "bf16" \
    --pretrained_model_name_or_path "stable-diffusion-v1-5/stable-diffusion-v1-5" \
    --output_dir "training_runs/sd15_corrupted_dpo" \
    --good_manifest "datasets/manifest/from_100k/good.json" \
    --dubious_manifest "datasets/manifest/from_100k/dubious.json" \
    --train_data_dir "datasets/FiFA-100k/data/train" \
    --flip_percentage 0.4 \
    --train_batch_size 8 \
    --gradient_accumulation_steps 8 \
    --dataloader_num_workers 4 \
    --max_train_steps 100 \
    --learning_rate 1e-5 \
    --checkpointing_steps 100 \
    --gradient_checkpointing \
    --report_to "wandb" \